const CodeDeploy = require('./CodeDeploy')
const Iam = require('./Iam')
const Lambda = require('./Lambda')
const ApiGateway = require('./ApiGateway')
const Sns = require('./Sns')
const S3 = require('./S3')
const CloudWatchEvents = require('./CloudWatchEvents')
const CloudWatchLogs = require('./CloudWatchLogs')
const Iot = require('./Iot')
const AppSync = require('./AppSyncDataSources')
const ElasticLoadBalancingV2 = require('./ElasticLoadBalancingV2')

module.exports.codeDeploy = CodeDeploy
module.exports.iam = Iam
module.exports.lambda = Lambda
module.exports.apiGateway = ApiGateway
module.exports.sns = Sns
module.exports.s3 = S3
module.exports.cloudWatchEvents = CloudWatchEvents
module.exports.cloudWatchLogs = CloudWatchLogs
module.exports.iot = Iot
module.exports.appSync = AppSync
module.exports.elasticLoadBalancingV2 = ElasticLoadBalancingV2
